
const Tasks = [
    {
      id: 1,
      title: 'Sample Task 1',
      description: 'This is a sample pending task.',
      startDate: '2024-03-28',
      status: 'Pending',
      assignee: 'John Doe',
      priority: 'P1',
    },
    {
      id: 2,
      title: 'Sample Task 2',
      description: 'This is a sample in-progress task.',
      startDate: '2024-03-28',
      status: 'In Progress',
      assignee: 'Jane Doe',
      priority: 'P1',
    },
    {
      id: 3,
      title: 'Sample Task 3',
      description: 'This is a sample completed task.',
      startDate: '2024-03-28',
      endDate: '2024-03-30',
      status: 'Completed',
      assignee: 'Emily Doe',
      priority: 'P0',
    },
    {
      id: 4,
      title: 'Sample Task 4',
      description: 'This is a sample deployed task.',
      startDate: '2024-03-28',
      status: 'Deployed',
      assignee: 'Mark Doe',
      priority: 'P1',
    },
    {
      id: 5,
      title: 'Sample Task 5',
      description: 'This is another sample pending task.',
      startDate: '2024-03-29',
      status: 'Pending',
      assignee: 'Alice Doe',
      priority: 'P2',
    },
    {
      id: 6,
      title: 'Sample Task 6',
      description: 'This is another sample in-progress task.',
      startDate: '2024-03-29',
      status: 'In Progress',
      assignee: 'Bob Doe',
      priority: 'P1',
    },
    {
      id: 7,
      title: 'Sample Task 7',
      description: 'This is another sample completed task.',
      startDate: '2024-03-29',
      endDate: '2024-03-31',
      status: 'Completed',
      assignee: 'Carol Doe',
      priority: 'P0',
    },
    {
      id: 8,
      title: 'Sample Task 8',
      description: 'This is another sample deployed task.',
      startDate: '2024-03-29',
      status: 'Deployed',
      assignee: 'Dave Doe',
      priority: 'P1',
    },
    {
      id: 9,
      title: 'Sample Task 9',
      description: 'This is yet another sample pending task.',
      startDate: '2024-03-30',
      status: 'Pending',
      assignee: 'Eve Doe',
      priority: 'P3',
    },
    {
      id: 10,
      title: 'Sample Task 10',
      description: 'This is yet another sample in-progress task.',
      startDate: '2024-03-30',
      status: 'In Progress',
      assignee: 'Frank Doe',
      priority: 'P1',
    },
    {
      id: 11,
      title: 'Sample Task 11',
      description: 'This is yet another sample completed task.',
      startDate: '2024-03-30',
      endDate: '2024-04-01',
      status: 'Completed',
      assignee: 'Grace Doe',
      priority: 'P0',
    },
    {
      id: 12,
      title: 'Sample Task 12',
      description: 'This is yet another sample deployed task.',
      startDate: '2024-03-30',
      status: 'Deployed',
      assignee: 'Hank Doe',
      priority: 'P1',
    },
    {
      id: 13,
      title: 'Sample Task 13',
      description: 'This is one more sample deferred taskaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.',
      startDate: '2024-03-31',
      status: 'Deferred',
      assignee: 'Ivy Doe',
      priority: 'P2',
    },
    {
      id: 14,
      title: 'Sample Task 14',
      description: 'This is one more sample pending task.',
      startDate: '2024-03-31',
      status: 'Pending',
      assignee: 'Jack Doe',
      priority: 'P2',
    },
    {
      id: 15,
      title: 'Sample Task 15',
      description: 'This is one more sample in-progress task.',
      startDate: '2024-03-31',
      status: 'In Progress',
      assignee: 'Kate Doe',
      priority: 'P1',
    },
    {
      id: 16,
      title: 'Sample Task 15',
      description: 'This is one more sample in-progress task.',
      startDate: '2024-03-31',
      status: 'Deffred',
      assignee: 'Kate Doe',
      priority: 'P1',
    },
  ];
  
  

  export default Tasks